controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    cartesian_pose_controller:
      type: cartesian_pose_controller/CartesianPoseController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
